### ISSUE TITLE
config XMLConfigurer is slowly and too many xstream instance waste of memory

### ISSUE THREAD

**Issue by cjdxhjj** [sebthom/oval#35]
according to your guide, i can use the flowing code to config validator
```xml
<beans>
  <bean id="validator" class="net.sf.oval.Validator">
    <constructor-arg>
      <list>
        <bean class="net.sf.oval.configuration.xml.XMLConfigurer">
           <constructor-arg type="java.io.InputStream" value="classpath:com/acme/OValConfiguration.xml" />
        </bean>
      </list>
    </constructor-arg>
  </bean>
</beans>
```

we must config the xml one by one, that is not a problem, i can config one dir, and get the xml config file in that dir, then by one loop, that work great, but here is xml configure

```java
public class XMLConfigurer implements Configurer {
   ...some code
   protected final Set<CheckInitializationListener> listeners = new LinkedHashSet<>(2);
   private POJOConfigurer pojoConfigurer = new POJOConfigurer();
   private final XStream xStream;

   /**
    * creates an XMLConfigurer instance backed by a new XStream instance
    * using the com.thoughtworks.xstream.io.xml.StaxDriver for XML parsing
    * if the StAX API is available
    *
    * @see com.thoughtworks.xstream.io.xml.StaxDriver
    */
   public XMLConfigurer() {
      xStream = new XStream(new XStreamReflectionProvider(), new XIncludeAwareDOMDriver());
      configureXStream();
   }

   public XMLConfigurer(final File xmlConfigFile) {
      this();
      fromXML(xmlConfigFile);
   }

   public XMLConfigurer(final InputStream xmlConfigStream) {
      this();
      fromXML(xmlConfigStream);
   }

   public XMLConfigurer(final Reader xmlConfigReader) {
      this();
      fromXML(xmlConfigReader);
   }

   public XMLConfigurer(final String xmlConfigAsString) {
      this();
      fromXML(xmlConfigAsString);
   }

   public boolean addCheckInitializationListener(final CheckInitializationListener listener) {
      Assert.argumentNotNull("listener", listener);
      return listeners.add(listener);
   }

   private void configureXStream() {
      XStream.setupDefaultSecurity(xStream);
      xStream.allowTypesByWildcard(new String[] {"net.sf.oval.**"});

      xStream.registerConverter(new ReflectionConverter(xStream.getMapper(), xStream.getReflectionProvider()) {
         @Override
         public Object unmarshal(final HierarchicalStreamReader reader, final UnmarshallingContext context) {
            final Object instance = super.unmarshal(reader, context);
            if (instance instanceof Check) {
               for (final CheckInitializationListener listener : listeners) {
                  listener.onCheckInitialized((Check) instance);
               }
            }
            return instance;
         }
      }, XStream.PRIORITY_VERY_LOW);
      xStream.registerConverter(new ListConverter(xStream.getMapper()));
      xStream.registerConverter(new AssertCheckConverter());
      xStream.registerConverter(new PatternConverter());

      xStream.omitField(AbstractCheck.class, "messageVariablesUpToDate");

      ..config xstream code
         }
      }
   }

   public void fromXML(final File input) {
      pojoConfigurer = (POJOConfigurer) xStream.fromXML(input);
   }

   public void fromXML(final InputStream input) {
      pojoConfigurer = (POJOConfigurer) xStream.fromXML(input);
   }

   public void fromXML(final Reader input) {
      pojoConfigurer = (POJOConfigurer) xStream.fromXML(input);
   }

   public void fromXML(final String input) {
      pojoConfigurer = (POJOConfigurer) xStream.fromXML(input);
   }

   @Override
   public ClassConfiguration getClassConfiguration(final Class<?> clazz) throws InvalidConfigurationException {
      return pojoConfigurer.getClassConfiguration(clazz);
   }

   @Override
   public ConstraintSetConfiguration getConstraintSetConfiguration(final String constraintSetId) throws InvalidConfigurationException {
      return pojoConfigurer.getConstraintSetConfiguration(constraintSetId);
   }

   public POJOConfigurer getPojoConfigurer() {
      return pojoConfigurer;
   }

   public XStream getXStream() {
      return xStream;
   }

   public boolean removeCheckInitializationListener(final CheckInitializationListener listener) {
      return listeners.remove(listener);
   }

   public void setPojoConfigurer(final POJOConfigurer pojoConfigurer) {
      this.pojoConfigurer = pojoConfigurer;
   }

   public synchronized String toXML() {
      return xStream.toXML(pojoConfigurer);
   }

   public synchronized void toXML(final OutputStream out) {
      xStream.toXML(pojoConfigurer, out);
   }

   public synchronized void toXML(final Writer out) {
      xStream.toXML(pojoConfigurer, out);
   }
}
```

 the construstor dos not need a exist xstream instance, it new a xstrem instance forever, and config it, it really slowly and unnecessary，we can use one xstream instance and config once, here is my solution

```kotlin
class XmlConfigurerFactory(private val xStream: XStream, private val xmlConfigs: Array<Resource>, private val converters: Array<ConverterMatcher>) {
    private val listeners: Set<CheckInitializationListener> = LinkedHashSet(2)
    val configurers: Collection<Configurer>
        get() {
            configureXStream()
            val configurers = ArrayList<Configurer>(xmlConfigs.size)
            for (resource in xmlConfigs) {
                try {
                    configurers.add(XMLConfigurer(xStream, resource))
                } catch (e: IOException) {
                    e.printStackTrace()
                }
            }
            return configurers
        }

    private class ListConverter(mapper: Mapper) : CollectionConverter(mapper) {
        override fun canConvert(type: Class<*>): Boolean = List::class.java.isAssignableFrom(type)
    }

    private fun configureXStream() {
        xStream.registerConverter(object : ReflectionConverter(xStream.mapper, xStream.reflectionProvider) {
            override fun unmarshal(reader: HierarchicalStreamReader, context: UnmarshallingContext): Any {
                val instance = super.unmarshal(reader, context)
                if (instance is Check)
                    for (listener in listeners)
                        listener.onCheckInitialized(instance)
                return instance
            }
        }, XStream.PRIORITY_VERY_LOW)
        if (converters.isNotEmpty()) {
            for (i in converters.indices) {
                when {
                    converters[i] is Converter -> xStream.registerConverter(this.converters[i] as Converter, i)
                    this.converters[i] is SingleValueConverter -> xStream.registerConverter(this.converters[i] as SingleValueConverter, i)
                    else -> throw IllegalArgumentException("Invalid ConverterMatcher [" + this.converters[i] + "]")
                }
            }
        }
        xStream.registerConverter(ListConverter(xStream.mapper))
        //xStream.registerConverter(AssertCheckConverter())
        xStream.omitField(AbstractCheck::class.java, "messageVariablesUpToDate")
        xStream.useAttributeFor(Class::class.java)
        xStream.useAttributeFor(Boolean::class.javaPrimitiveType)
        xStream.useAttributeFor(Byte::class.javaPrimitiveType)
        xStream.useAttributeFor(Char::class.javaPrimitiveType)
        xStream.useAttributeFor(Double::class.javaPrimitiveType)
        xStream.useAttributeFor(Float::class.javaPrimitiveType)
        xStream.useAttributeFor(Int::class.javaPrimitiveType)
        xStream.useAttributeFor(Long::class.javaPrimitiveType)
        xStream.useAttributeFor(Boolean::class.java)
        xStream.useAttributeFor(Byte::class.java)
        xStream.useAttributeFor(Char::class.java)
        xStream.useAttributeFor(Double::class.java)
        xStream.useAttributeFor(Float::class.java)
        xStream.useAttributeFor(Int::class.java)
        xStream.useAttributeFor(Long::class.java)
        xStream.useAttributeFor(String::class.java)
        xStream.alias("java-type", Class::class.java)
        xStream.alias("constraintTarget", ConstraintTarget::class.java)
        // constraint check short forms
        xStream.alias("assert", AssertCheck::class.java)
        xStream.alias("assertConstraintSet", AssertConstraintSetCheck::class.java)
        xStream.alias("assertFalse", AssertFalseCheck::class.java)
        xStream.alias("assertFieldConstraints", AssertFieldConstraintsCheck::class.java)
        xStream.alias("assertNull", AssertNullCheck::class.java)
        xStream.alias("assertTrue", AssertTrueCheck::class.java)
        run {
            xStream.alias("assertURL", AssertURLCheck::class.java)
            xStream.alias("permittedURIScheme", AssertURLCheck.URIScheme::class.java)
            xStream.addImplicitCollection(AssertURLCheck::class.java, "permittedURISchemes", AssertURLCheck.URIScheme::class.java)
        }
        xStream.alias("assertValid", AssertValidCheck::class.java)
        xStream.alias("checkWith", CheckWithCheck::class.java)
        xStream.alias("dateRange", DateRangeCheck::class.java)
        xStream.alias("digits", DigitsCheck::class.java)
        xStream.alias("email", EmailCheck::class.java)
        xStream.alias("equalToField", EqualToFieldCheck::class.java)
        xStream.alias("future", FutureCheck::class.java)
        xStream.alias("hasSubstring", HasSubstringCheck::class.java)
        xStream.alias("instanceOf", InstanceOfCheck::class.java)
        xStream.alias("instanceOfAny", InstanceOfAnyCheck::class.java)
        xStream.alias("length", LengthCheck::class.java)
        run {
            xStream.alias("matchPattern", MatchPatternCheck::class.java)
            xStream.alias("pattern", Pattern::class.java)
            xStream.addImplicitCollection(MatchPatternCheck::class.java, "patterns", Pattern::class.java)
        }
        xStream.alias("max", MaxCheck::class.java)
        xStream.alias("maxLength", MaxLengthCheck::class.java)
        xStream.alias("maxSize", MaxSizeCheck::class.java)
        xStream.alias("memberOf", MemberOfCheck::class.java)
        xStream.alias("min", MinCheck::class.java)
        xStream.alias("minLength", MinLengthCheck::class.java)
        xStream.alias("minSize", MinSizeCheck::class.java)
        xStream.alias("noSelfReference", NoSelfReferenceCheck::class.java)
        xStream.alias("notBlank", NotBlankCheck::class.java)
        xStream.alias("notEmpty", NotEmptyCheck::class.java)
        xStream.alias("notEqual", NotEqualCheck::class.java)
        xStream.alias("notEqualToField", NotEqualToFieldCheck::class.java)
        run {
            xStream.alias("notMatchPattern", NotMatchPatternCheck::class.java)
            xStream.addImplicitCollection(NotMatchPatternCheck::class.java, "patterns", Pattern::class.java)
        }
        xStream.alias("notMemberOf", NotMemberOfCheck::class.java)
        xStream.alias("notNegative", NotNegativeCheck::class.java)
        xStream.alias("notNull", NotNullCheck::class.java)
        xStream.alias("past", PastCheck::class.java)
        xStream.alias("range", RangeCheck::class.java)
        xStream.alias("simpleCheck", CheckWithCheck.SimpleCheck::class.java)
        xStream.alias("size", SizeCheck::class.java)
        xStream.alias("validateWithMethod", ValidateWithMethodCheck::class.java)
        // check exclusions short forms
        xStream.alias("nullable", NullableExclusion::class.java)
        // <oval> -> net.sf.oval.configuration.POJOConfigurer
        xStream.alias("oval", POJOConfigurer::class.java)
        run {
            // <constraintSet> -> net.sf.oval.configuration.elements.ConstraintSetConfiguration
            xStream.addImplicitCollection(POJOConfigurer::class.java, "constraintSetConfigurations", ConstraintSetConfiguration::class.java)
            xStream.alias("constraintSet", ConstraintSetConfiguration::class.java)
            xStream.addImplicitCollection(ConstraintSetConfiguration::class.java, "checks")

            // <class> -> net.sf.oval.configuration.elements.ClassConfiguration
            xStream.addImplicitCollection(POJOConfigurer::class.java, "classConfigurations", ClassConfiguration::class.java)
            xStream.alias("class", ClassConfiguration::class.java)
            run {
                // <object> -> net.sf.oval.configuration.elements.ObjectConfiguration
                xStream.aliasField("object", ClassConfiguration::class.java, "objectConfiguration")
                run { xStream.addImplicitCollection(ObjectConfiguration::class.java, "checks") }
                // <field> -> net.sf.oval.configuration.elements.FieldConfiguration
                xStream.addImplicitCollection(ClassConfiguration::class.java, "fieldConfigurations", FieldConfiguration::class.java)
                xStream.alias("field", FieldConfiguration::class.java)
                xStream.addImplicitCollection(FieldConfiguration::class.java, "checks")
                // <parameter> -> net.sf.oval.configuration.elements.ParameterConfiguration
                // used within ConstructorConfiguration and MethodConfiguration
                xStream.alias("parameter", ParameterConfiguration::class.java)
                xStream.addImplicitCollection(ParameterConfiguration::class.java, "checks", Check::class.java)
                xStream.addImplicitCollection(ParameterConfiguration::class.java, "checkExclusions", CheckExclusion::class.java)
                // <constructor> -> net.sf.oval.configuration.elements.ConstructorConfiguration
                xStream.addImplicitCollection(ClassConfiguration::class.java, "constructorConfigurations", ConstructorConfiguration::class.java)
                xStream.alias("constructor", ConstructorConfiguration::class.java)
                run {
                    // <parameter> -> net.sf.oval.configuration.elements.ParameterConfiguration
                    xStream.addImplicitCollection(ConstructorConfiguration::class.java, "parameterConfigurations", ParameterConfiguration::class.java)
                }
                // <method> -> net.sf.oval.configuration.elements.MethodConfiguration
                xStream.addImplicitCollection(ClassConfiguration::class.java, "methodConfigurations", MethodConfiguration::class.java)
                xStream.alias("method", MethodConfiguration::class.java)
                run {
                    // <parameter> -> net.sf.oval.configuration.elements.ParameterConfiguration
                    xStream.addImplicitCollection(MethodConfiguration::class.java, "parameterConfigurations", ParameterConfiguration::class.java)
                    // <returnValue> -> net.sf.oval.configuration.elements.MethodConfiguration.returnValueConfiguration
                    // -> MethodReturnValueConfiguration
                    xStream.aliasField("returnValue", MethodConfiguration::class.java, "returnValueConfiguration")
                    xStream.addImplicitCollection(MethodReturnValueConfiguration::class.java, "checks", Check::class.java)
                    // <pre> -> net.sf.oval.configuration.elements.MethodConfiguration.preExecutionConfiguration ->
                    // MethodPreExecutionConfiguration
                    xStream.aliasField("preExecution", MethodConfiguration::class.java, "preExecutionConfiguration")
                    xStream.addImplicitCollection(MethodPreExecutionConfiguration::class.java, "checks", PreCheck::class.java)
                    xStream.alias("pre", PreCheck::class.java)
                    // <post> -> net.sf.oval.configuration.elements.MethodConfiguration.postExecutionConfiguration ->
                    // MethodPostExecutionConfiguration
                    xStream.aliasField("postExecution", MethodConfiguration::class.java, "postExecutionConfiguration")
                    xStream.addImplicitCollection(MethodPostExecutionConfiguration::class.java, "checks", PostCheck::class.java)
                    xStream.alias("post", PostCheck::class.java)
                }
            }
        }
    }
}
````

here is my xmlconfigure

```kotlin
class XMLConfigurer(xStream: XStream, xmlConfig: Resource): Configurer{
    private val configurer: POJOConfigurer = xStream.fromXML(xmlConfig.inputStream) as POJOConfigurer

    @Throws(InvalidConfigurationException::class)
    override fun getClassConfiguration(clazz: Class<*>): ClassConfiguration? = configurer.getClassConfiguration(clazz)

    @Throws(InvalidConfigurationException::class)
    override fun getConstraintSetConfiguration(constraintSetId: String): ConstraintSetConfiguration? = configurer.getConstraintSetConfiguration(constraintSetId)
}
```

i modify the xmlconfigure, it simply, and provider an factory, it allow pass one xstream instance, your can make it optional, config that xstream once and config the passed recource one by one to an list xmlconfifure, and my usage is here

```kotlin
    @Bean
    fun ovalGuardInterceptor(): GuardInterceptor = XmlConfigurerFactory(XStream(), PathMatchingResourcePatternResolver().getResources("classpath:validation/*/*.xml"), arrayOf(RegexPatternConverter())).run {
        Guard(this.configurers)
    }.run { GuardInterceptor(this) }

    @Bean
    fun guardAdviceAdvisor(ovalGuardInterceptor: GuardInterceptor): Advisor = AspectJExpressionPointcut().apply { expression = "execution(public * xx.xx.service.impl.*.*(..))" }.run { DefaultPointcutAdvisor(this, ovalGuardInterceptor).also { it.order = 0 } }
```

the converter may remove since 2.0.1, it fix the xstream pattern config error

**Comment by sebthom** [comment]
Can you give 2.0.2-SNAPSHOT a try? It allows you to share the XStream instance. E.g.

```java
XStream xStream = XMLConfigurer.createXStream();
XMLConfigurer cfg1 = new XMLConfigurer(xStream, "myConfig1.xml");
XMLConfigurer cfg2 = new XMLConfigurer(xStream, "myConfig2.xml");
```

The snapshot maven repo is here https://raw.githubusercontent.com/sebthom/oval/mvn-snapshots-repo/

**Comment by cjdxhjj** [comment]
thanks, i will try for it

**Comment by cjdxhjj** [comment]
can you publish that release, i can't fetch it from mvn or jcenter.

**Comment by sebthom** [comment]
I can build a release I just wanted to check first, that this is what you are looking for. you can also manually download these jar from here: https://github.com/sebthom/oval/tree/mvn-snapshots-repo/net/sf/oval/oval/2.0.2-SNAPSHOT

**Comment by cjdxhjj** [comment]
wait for a monment, i' m in china, is not able access to the github maven repo, i would make a proxy to test it

**Comment by cjdxhjj** [comment]
when i upgrade to 2.0.2-SNAPSHOT, it startup fail,

> cause-exception     : com.thoughtworks.xstream.security.ForbiddenClassException
cause-message       : cn.dbn.userCenter.check.LoginNameCheck
class               : net.sf.oval.constraint.CheckWithCheck
required-type       : net.sf.oval.constraint.CheckWithCheck
converter-type      : net.sf.oval.configuration.xml.XMLConfigurer$1
path                : /oval/class/field[2]/checkWith/simpleCheck
class[1]            : net.sf.oval.configuration.pojo.elements.FieldConfiguration
required-type[1]    : net.sf.oval.configuration.pojo.elements.FieldConfiguration
class[2]            : net.sf.oval.configuration.pojo.elements.ClassConfiguration
required-type[2]    : net.sf.oval.configuration.pojo.elements.ClassConfiguration
class[3]            : net.sf.oval.configuration.pojo.POJOConfigurer
required-type[3]    : net.sf.oval.configuration.pojo.POJOConfigurer
version             : 1.4.11.1
-------------------------------
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1171)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 36 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [net.sf.oval.guard.GuardInterceptor]: Factory method 'ovalGuardInterceptor' threw exception; nested exception is com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----

that report that the user customer check is not allowed by xstrem, please open an interface to add the allow list
in your code
`
public static XStream createXStream() {
      final XStream xStream = new XStream(new XStreamReflectionProvider(), new XIncludeAwareDOMDriver());
      XStream.setupDefaultSecurity(xStream);
      xStream.allowTypesByWildcard(new String[] {"net.sf.oval.**"});

      xStream.registerConverter(new ReflectionConverter(xStream.getMapper(), xStream.getReflectionProvider()) {
         @Override
         public Object unmarshal(final HierarchicalStreamReader reader, final UnmarshallingContext context) {
            final Object instance = super.unmarshal(reader, context);
            if (instance instanceof Check) {
               onCheckInitialized((Check) instance);
            }
            return instance;
         }
      }, XStream.PRIORITY_VERY_LOW);
...
}
`

**Comment by sebthom** [comment]
I think you can simply call
```kotlin
fun ovalGuardInterceptor(): GuardInterceptor {
    val xStream = XMLConfigurer.createXStream()
    xStream.allowTypesByWildcard(arrayOf("mypackage.**"))
    return PathMatchingResourcePatternResolver().getResources("classpath:validation/*/*.xml").map { XMLConfigurer(xStream, it.inputStream) }.run { GuardInterceptor(Guard(this)) }
}
```

**Comment by cjdxhjj** [comment]
it works, i think that method can only invoke once at first, and did not check the code

**Comment by cjdxhjj** [comment]
can you release it? i test it with my local package, it can't deploy by ci, 2.0.1 has no way to config xstream, when project use custome check, it will fail.

**Comment by sebthom** [comment]
@cjdxhjj I released version 2.1.0.

**Comment by cjdxhjj** [comment]
thanks very much

**Comment by bharattrikha03** [comment]
After reading the above comment i have upgraded the OVal to 2.1.0 from 2.0.1 still getting the below error . 

Caused by: com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.security.ForbiddenClassException
cause-message       : com.aon.salesforce.validator.oval.constraint.CustomDateFormatCheck
class               : net.sf.oval.configuration.pojo.elements.FieldConfiguration
required-type       : net.sf.oval.configuration.pojo.elements.FieldConfiguration
converter-type      : net.sf.oval.configuration.xml.XMLConfigurer$1
path                : /oval/class/field[2]/com.aon.salesforce.validator.oval.constraint.CustomDateFormatCheck
class[1]            : net.sf.oval.configuration.pojo.elements.ClassConfiguration
required-type[1]    : net.sf.oval.configuration.pojo.elements.ClassConfiguration
class[2]            : net.sf.oval.configuration.pojo.POJOConfigurer
required-type[2]    : net.sf.oval.configuration.pojo.POJOConfigurer
version             : 1.4.11.1
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:77)

**Comment by bharattrikha03** [comment]
Downloaded the Oval jar from below path 
https://jcenter.bintray.com/net/sf/oval/oval/2.1.0/

**Comment by sebthom** [comment]
@bharattrikha03 this is not a bug in oval but a security feature in newer versions of the underlying XStream serialization library and happens for custom constraints.

You need to instantiate the validator something like this:
```java
XStream xstream = XMLConfigurer.createXStream();
xstream.allowTypesByWildcard(new String[] {"com.aon.salesforce.validator.oval.constraint.**"}));
XMLConfigurer config = new XMLConfigurer(xStream, new File("myconfig.xml"));
Validator v = new Validator(config);
```

**Comment by bharattrikha03** [comment]
@sebthom I have integrated the Oval framework with my Spring Application . Could you please give me a border idea how to instantiate the validator because i have already configured it according to the user manual . Please Find the below oval configuration and my Custom Constraint

 <bean id="ovalValidator" class="net.sf.oval.Validator">
	<constructor-arg>
		<list>
			<bean class="net.sf.oval.configuration.xml.XMLConfigurer">
				<constructor-arg type="java.io.InputStream"
					value="file:///${prprConfigRoot}/databinder/OvalXMLConfiguration.xml" />
			</bean>
		</list>
	</constructor-arg>
</bean> 


[CustomDateFormatCheck1.txt](https://github.com/sebthom/oval/files/4659438/CustomDateFormatCheck1.txt)

**Comment by sebthom** [comment]
@bharattrikha03 This gets complicated with Spring's legacy XML based configuration, you would need to utilize `org.springframework.beans.factory.config.MethodInvokingBean` somehow along the way.

So better migrate to Spring's annotation based configuration, where you could easily do something like:
```java
@Configuration
class MySpringConfig {

  @Bean
  public Validator validator(@Value("${prprConfigRoot}") String prprConfigRoot) {
    XStream xstream = XMLConfigurer.createXStream();
	xstream.allowTypesByWildcard(new String[] {
      "com.aon.salesforce.validator.oval.constraint.**"
    }));
	XMLConfigurer xmlConfig = new XMLConfigurer(
      xStream, 
      new File(prprConfigRoot + "/databinder/OvalXMLConfiguration.xml")
    );
    return new Validator(xmlConfig);
  }
}
```

If you haven't used annotation driven config, maybe this helps https://www.tutorialspoint.com/spring/spring_java_based_configuration.htm

**Comment by bharattrikha03** [comment]
Thanks @sebthom I will Try this
